services:
  royalxpay-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: royalxpay-app
    ports:
      - "8080:80"
    # volumes:
    #   - ./writable:/var/www/html/writable
    #   - ./public/uploads:/var/www/html/public/uploads
    environment:
      - CI_ENVIRONMENT=staging
      - DB_HOSTNAME=host.docker.internal
      - DB_NAME=royalxpay
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_PORT=3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - royalxpay-network

networks:
  royalxpay-network:
    driver: bridge
